name: Rodar Bot Discord

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *" # roda a cada 10 minutos (opcional)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Rodar Bot
        run: python bot.py

